import os
import docx
from docx.shared import Pt

# List of paragraphs to insert. 
# Each entry is a tuple: (text, style, is_code_block, space_before, space_after)
PARAGRAPHS_TO_INSERT = [
    ("To deploy and execute the interactive credit decision simulation dashboard locally, developers and users must first establish a clean Python runtime environment. It is highly recommended to create an isolated Python virtual environment to avoid package dependency conflicts. The project is fully compatible with Python 3.9 through Python 3.12.", "Normal", False, 6, 6),
    ("To initialize the local environment, clone the repository from GitHub, create a virtual environment, and install all package dependencies listed in requirements.txt. Run the following shell commands in order:", "Normal", False, 6, 6),
    ("git clone https://github.com/alisokullu/EXPLAINABLE-NEURAL-NETWORKS-IN-CREDIT-DECISIONS.git\ncd EXPLAINABLE-NEURAL-NETWORKS-IN-CREDIT-DECISIONS\npython -m venv venv\nvenv\\Scripts\\activate      # For Windows Command Prompt/PowerShell\n# source venv/bin/activate # For macOS/Linux\npip install -r requirements.txt", "Consolas", True, 6, 6),
    ("Once the dependencies are installed, you can optionally run the data cleaning, training, and explanation precalculation scripts to re-generate the pipeline artifacts (these are already pre-generated and stored in the artifacts/ directory by default):", "Normal", False, 6, 6),
    ("python clean_datasets.py              # Runs raw data cleaning\npython train_dnn.py                    # Trains HELOC PyTorch DNN model\npython train_german_dnn.py             # Trains German Credit PyTorch DNN model\npython generate_shap.py                # Precalculates global SHAP explanations\npython generate_lime.py                # Precalculates global LIME explanations\npython generate_ig.py                  # Precalculates Integrated Gradients\npython generate_counterfactuals.py     # Precalculates DiCE counterfactuals", "Consolas", True, 6, 6),
    ("To start the web application and launch the interactive simulation dashboard locally, run the following Streamlit command in the terminal:", "Normal", False, 6, 6),
    ("streamlit run dashboard.py", "Consolas", True, 6, 6),
    ("Upon execution, the local Streamlit server starts a background service, hosting the interface on local port 8501. The console will display the local network addresses. The user can open any modern web browser and navigate to the indicated local address, which will automatically load the graphical dashboard interface.", "Normal", False, 6, 6),
    ("The simulation dashboard is divided into four main functional panels to facilitate credit review and explainability analysis:", "Normal", False, 6, 6),
    ("Overview Dashboard: Displays model performance statistics, training histories, and interactive confusion matrices for both datasets.", "Bullet", False, 3, 3),
    ("Explainer Comparison: Visualizes global feature importances across SHAP, LIME, and Integrated Gradients, allowing users to benchmark explanation stability and consistency.", "Bullet", False, 3, 3),
    ("Case-Level Inspector: Allows credit officers to select individual loan applicants, inspect their default risk scores, view local explanations (SHAP force plots, local LIME bars, and Integrated Gradients), and explore actionability-aware counterfactual recourse paths generated by DiCE.", "Bullet", False, 3, 3),
    ("Fairness Audit: Conducts demographic parity and equalized odds fairness evaluations on the model's decisions, showing the impact of threshold optimization on group fairness metrics.", "Bullet", False, 3, 3)
]

def update_docx(file_path):
    if not os.path.exists(file_path):
        print(f"Skipping: {file_path} (File not found)")
        return
        
    print(f"Updating: {file_path}")
    try:
        doc = docx.Document(file_path)
    except Exception as e:
        print(f"Error opening {file_path}: {e}")
        return
        
    idx_b = None
    idx_c = None
    for idx, p in enumerate(doc.paragraphs):
        if p.style.name == 'Heading 1' and p.text.strip().startswith('APPENDIX B:'):
            idx_b = idx
        if p.style.name == 'Heading 1' and p.text.strip().startswith('APPENDIX C:'):
            idx_c = idx
            break
            
    if idx_b is None or idx_c is None:
        print("Error: APPENDIX B or APPENDIX C heading not found.")
        return
        
    # Identify which paragraphs to delete.
    # We want to delete the paragraphs from idx_b + 1 up to the paragraph before the image paragraph.
    # Let's find the paragraph with the image.
    img_idx = None
    for idx in range(idx_b + 1, idx_c):
        p = doc.paragraphs[idx]
        has_image = False
        for run in p.runs:
            if run.element.findall('.//{http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing}inline'):
                has_image = True
                break
        if has_image:
            img_idx = idx
            break
            
    if img_idx is None:
        print("Warning: Dashboard screenshot image paragraph not found. Deleting all text until APPENDIX C.")
        img_idx = idx_c
        
    print(f"Deleting old text paragraphs between indices {idx_b + 1} and {img_idx - 1}...")
    to_delete = [doc.paragraphs[i] for i in range(idx_b + 1, img_idx)]
    
    # Delete them
    for p in to_delete:
        p_element = p._p
        parent = p_element.getparent()
        parent.remove(p_element)
        
    # Now we insert our new paragraphs below the Appendix B heading
    heading_p = doc.paragraphs[idx_b]
    parent = heading_p._p.getparent()
    current_insert_idx = parent.index(heading_p._p) + 1
    
    for text, style_name, is_code_block, space_before, space_after in PARAGRAPHS_TO_INSERT:
        p = doc.add_paragraph()
        p.style = 'Normal'
        p.paragraph_format.space_before = Pt(space_before)
        p.paragraph_format.space_after = Pt(space_after)
        p.paragraph_format.line_spacing = 1.15
        
        if is_code_block:
            # Code block formatting (gray background, indented, consolas font)
            # In python-docx we can indent the paragraph
            p.paragraph_format.left_indent = Pt(18)
            p.paragraph_format.right_indent = Pt(18)
            
            run = p.add_run(text)
            run.font.name = 'Consolas'
            run.font.size = Pt(9.5)
            
        elif style_name == "Bullet":
            # Add bullet manually
            bullet_run = p.add_run("•  ")
            bullet_run.font.name = 'Calibri'
            bullet_run.font.size = Pt(11)
            
            # Split key term from explanation
            if ":" in text:
                term, explanation = text.split(":", 1)
                bold_run = p.add_run(term)
                bold_run.bold = True
                bold_run.font.name = 'Calibri'
                bold_run.font.size = Pt(11)
                
                colon_run = p.add_run(":")
                colon_run.font.name = 'Calibri'
                colon_run.font.size = Pt(11)
                
                desc_run = p.add_run(explanation)
                desc_run.font.name = 'Calibri'
                desc_run.font.size = Pt(11)
            else:
                desc_run = p.add_run(text)
                desc_run.font.name = 'Calibri'
                desc_run.font.size = Pt(11)
        else:
            run = p.add_run(text)
            run.font.name = 'Calibri'
            run.font.size = Pt(11)
            
        parent.insert(current_insert_idx, p._p)
        current_insert_idx += 1
        
    # Save the document
    try:
        doc.save(file_path)
        print("Successfully updated and saved the document!")
    except PermissionError:
        print(f"Error: {file_path} is currently locked or open. Please close Microsoft Word and try again.")
    except Exception as e:
        print(f"Error saving {file_path}: {e}")

def main():
    paths = [
        r'c:/Users/aliso/Downloads/xai-credit-decision-main/4992FinalReport1011165.docx',
        r'c:/Users/aliso/Downloads/xai-credit-decision-main/4992FinalReport1011165_updated.docx'
    ]
    for path in paths:
        update_docx(path)

if __name__ == '__main__':
    main()
